using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class DB_EnemyStat : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4923325311412840363UL,12779677772499145875UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.Double F_MaxHP
	{
		get => _F_MaxHP[Index];
		set => _F_MaxHP.SetValue(this, value);
	}
	public System.Double F_AttackDamage
	{
		get => _F_AttackDamage[Index];
		set => _F_AttackDamage.SetValue(this, value);
	}
	public System.Single F_MoveSpeed
	{
		get => _F_MoveSpeed[Index];
		set => _F_MoveSpeed.SetValue(this, value);
	}
	public System.Double F_GoldReward
	{
		get => _F_GoldReward[Index];
		set => _F_GoldReward.SetValue(this, value);
	}
	public System.Double F_Exp
	{
		get => _F_Exp[Index];
		set => _F_Exp.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268299810694595612UL, 12778986858213343882UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_MaxHP;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_MaxHP => _ufle12jhs77_F_MaxHP ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5129162824064087256UL, 17783174223074220204UL), () => _ufle12jhs77_F_MaxHP = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_AttackDamage;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_AttackDamage => _ufle12jhs77_F_AttackDamage ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5617600402046563158UL, 6336425040502012068UL), () => _ufle12jhs77_F_AttackDamage = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_MoveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_MoveSpeed => _ufle12jhs77_F_MoveSpeed ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5458529972999440393UL, 16262318388670659735UL), () => _ufle12jhs77_F_MoveSpeed = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_GoldReward;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_GoldReward => _ufle12jhs77_F_GoldReward ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5247242173194927400UL, 1612438593962469767UL), () => _ufle12jhs77_F_GoldReward = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_Exp;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_Exp => _ufle12jhs77_F_Exp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4779789710921941776UL, 4150966925177304497UL), () => _ufle12jhs77_F_Exp = null);
	private DB_EnemyStat() : base(MetaDefault) {}
	private DB_EnemyStat(BGId id) : base(MetaDefault, id) {}
	private DB_EnemyStat(BGMetaEntity meta) : base(meta) {}
	private DB_EnemyStat(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_EnemyStat FindEntity(Predicate<DB_EnemyStat> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_EnemyStat> FindEntities(Predicate<DB_EnemyStat> filter, List<DB_EnemyStat> result=null, Comparison<DB_EnemyStat> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_EnemyStat> action, Predicate<DB_EnemyStat> filter=null, Comparison<DB_EnemyStat> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_EnemyStat GetEntity(BGId entityId) => (DB_EnemyStat) MetaDefault.GetEntity(entityId);
	public static DB_EnemyStat GetEntity(int index) => (DB_EnemyStat) MetaDefault[index];
	public static DB_EnemyStat GetEntity(string entityName) => (DB_EnemyStat) MetaDefault.GetEntity(entityName);
	public static DB_EnemyStat NewEntity() => (DB_EnemyStat) MetaDefault.NewEntity();
	public static DB_EnemyStat NewEntity(BGId entityId) => (DB_EnemyStat) MetaDefault.NewEntity(entityId);
	public static DB_EnemyStat NewEntity(Action<DB_EnemyStat> callback) => (DB_EnemyStat) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_EnemyStat)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4923325311412840363UL,12779677772499145875UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5268299810694595612UL, 12778986858213343882UL));
		_ufle12jhs77_F_MaxHP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5129162824064087256UL, 17783174223074220204UL));
		_ufle12jhs77_F_AttackDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5617600402046563158UL, 6336425040502012068UL));
		_ufle12jhs77_F_MoveSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5458529972999440393UL, 16262318388670659735UL));
		_ufle12jhs77_F_GoldReward = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5247242173194927400UL, 1612438593962469767UL));
		_ufle12jhs77_F_Exp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(4779789710921941776UL, 4150966925177304497UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_MaxHP = null;
		_ufle12jhs77_F_AttackDamage = null;
		_ufle12jhs77_F_MoveSpeed = null;
		_ufle12jhs77_F_GoldReward = null;
		_ufle12jhs77_F_Exp = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_EnemyStat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_EnemyStat(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "EnemyStat";
		public const string name = "name";
		public const string MaxHP = "MaxHP";
		public const string AttackDamage = "AttackDamage";
		public const string MoveSpeed = "MoveSpeed";
		public const string GoldReward = "GoldReward";
		public const string Exp = "Exp";
	}
}

[Preserve]
public sealed partial class DB_StageStat : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4726363427288546035UL,8723317037712985742UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.Int32 F_StageId
	{
		get => _F_StageId[Index];
		set => _F_StageId.SetValue(this, value);
	}
	public System.String F_EnemyStatId
	{
		get => _F_EnemyStatId[Index];
		set => _F_EnemyStatId[Index] = value;
	}
	public System.String F_BossStatId
	{
		get => _F_BossStatId[Index];
		set => _F_BossStatId[Index] = value;
	}
	public System.Single F_HpMultiplier
	{
		get => _F_HpMultiplier[Index];
		set => _F_HpMultiplier.SetValue(this, value);
	}
	public System.Single F_AttackMultiplier
	{
		get => _F_AttackMultiplier[Index];
		set => _F_AttackMultiplier.SetValue(this, value);
	}
	public System.Single F_SpeedMultiplier
	{
		get => _F_SpeedMultiplier[Index];
		set => _F_SpeedMultiplier.SetValue(this, value);
	}
	public System.Single F_GoldMultiplier
	{
		get => _F_GoldMultiplier[Index];
		set => _F_GoldMultiplier.SetValue(this, value);
	}
	public System.Single F_ExpMultiplier
	{
		get => _F_ExpMultiplier[Index];
		set => _F_ExpMultiplier.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5261930319687192274UL, 15592654722136220564UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_StageId;
	public static BansheeGz.BGDatabase.BGFieldInt _F_StageId => _ufle12jhs77_F_StageId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4950306653884979068UL, 3309796411598320283UL), () => _ufle12jhs77_F_StageId = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_EnemyStatId;
	public static BansheeGz.BGDatabase.BGFieldString _F_EnemyStatId => _ufle12jhs77_F_EnemyStatId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5720306326938904020UL, 2841415780394115495UL), () => _ufle12jhs77_F_EnemyStatId = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_BossStatId;
	public static BansheeGz.BGDatabase.BGFieldString _F_BossStatId => _ufle12jhs77_F_BossStatId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5674789623623500459UL, 16553473708059325101UL), () => _ufle12jhs77_F_BossStatId = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_HpMultiplier;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_HpMultiplier => _ufle12jhs77_F_HpMultiplier ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5321776302266293487UL, 4873400290812826291UL), () => _ufle12jhs77_F_HpMultiplier = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_AttackMultiplier;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_AttackMultiplier => _ufle12jhs77_F_AttackMultiplier ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4756408081179050917UL, 12145209261706060476UL), () => _ufle12jhs77_F_AttackMultiplier = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_SpeedMultiplier;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_SpeedMultiplier => _ufle12jhs77_F_SpeedMultiplier ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5065038072319742958UL, 2262494868768001713UL), () => _ufle12jhs77_F_SpeedMultiplier = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_GoldMultiplier;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_GoldMultiplier => _ufle12jhs77_F_GoldMultiplier ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5655657416584089914UL, 2480428909955851165UL), () => _ufle12jhs77_F_GoldMultiplier = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_ExpMultiplier;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_ExpMultiplier => _ufle12jhs77_F_ExpMultiplier ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4632068294852262613UL, 7469475607775434634UL), () => _ufle12jhs77_F_ExpMultiplier = null);
	private DB_StageStat() : base(MetaDefault) {}
	private DB_StageStat(BGId id) : base(MetaDefault, id) {}
	private DB_StageStat(BGMetaEntity meta) : base(meta) {}
	private DB_StageStat(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_StageStat FindEntity(Predicate<DB_StageStat> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_StageStat> FindEntities(Predicate<DB_StageStat> filter, List<DB_StageStat> result=null, Comparison<DB_StageStat> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_StageStat> action, Predicate<DB_StageStat> filter=null, Comparison<DB_StageStat> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_StageStat GetEntity(BGId entityId) => (DB_StageStat) MetaDefault.GetEntity(entityId);
	public static DB_StageStat GetEntity(int index) => (DB_StageStat) MetaDefault[index];
	public static DB_StageStat GetEntity(string entityName) => (DB_StageStat) MetaDefault.GetEntity(entityName);
	public static DB_StageStat NewEntity() => (DB_StageStat) MetaDefault.NewEntity();
	public static DB_StageStat NewEntity(BGId entityId) => (DB_StageStat) MetaDefault.NewEntity(entityId);
	public static DB_StageStat NewEntity(Action<DB_StageStat> callback) => (DB_StageStat) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_StageStat)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4726363427288546035UL,8723317037712985742UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5261930319687192274UL, 15592654722136220564UL));
		_ufle12jhs77_F_StageId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4950306653884979068UL, 3309796411598320283UL));
		_ufle12jhs77_F_EnemyStatId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5720306326938904020UL, 2841415780394115495UL));
		_ufle12jhs77_F_BossStatId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5674789623623500459UL, 16553473708059325101UL));
		_ufle12jhs77_F_HpMultiplier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5321776302266293487UL, 4873400290812826291UL));
		_ufle12jhs77_F_AttackMultiplier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4756408081179050917UL, 12145209261706060476UL));
		_ufle12jhs77_F_SpeedMultiplier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5065038072319742958UL, 2262494868768001713UL));
		_ufle12jhs77_F_GoldMultiplier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5655657416584089914UL, 2480428909955851165UL));
		_ufle12jhs77_F_ExpMultiplier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4632068294852262613UL, 7469475607775434634UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_StageId = null;
		_ufle12jhs77_F_EnemyStatId = null;
		_ufle12jhs77_F_BossStatId = null;
		_ufle12jhs77_F_HpMultiplier = null;
		_ufle12jhs77_F_AttackMultiplier = null;
		_ufle12jhs77_F_SpeedMultiplier = null;
		_ufle12jhs77_F_GoldMultiplier = null;
		_ufle12jhs77_F_ExpMultiplier = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_StageStat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_StageStat(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "StageStat";
		public const string name = "name";
		public const string StageId = "StageId";
		public const string EnemyStatId = "EnemyStatId";
		public const string BossStatId = "BossStatId";
		public const string HpMultiplier = "HpMultiplier";
		public const string AttackMultiplier = "AttackMultiplier";
		public const string SpeedMultiplier = "SpeedMultiplier";
		public const string GoldMultiplier = "GoldMultiplier";
		public const string ExpMultiplier = "ExpMultiplier";
	}
}

[Preserve]
public sealed partial class DB_SwordStat : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5409651157038217224UL,8990331384380502203UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.Double F_AttackDamage
	{
		get => _F_AttackDamage[Index];
		set => _F_AttackDamage.SetValue(this, value);
	}
	public System.Single F_Cooldown
	{
		get => _F_Cooldown[Index];
		set => _F_Cooldown.SetValue(this, value);
	}
	public System.Single F_MoveSpeed
	{
		get => _F_MoveSpeed[Index];
		set => _F_MoveSpeed.SetValue(this, value);
	}
	public System.Single F_CritDamage
	{
		get => _F_CritDamage[Index];
		set => _F_CritDamage.SetValue(this, value);
	}
	public System.Single F_CritChance
	{
		get => _F_CritChance[Index];
		set => _F_CritChance.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5393742928008535207UL, 12160457354885359032UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_AttackDamage;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_AttackDamage => _ufle12jhs77_F_AttackDamage ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4719671630520485392UL, 13677255214246859924UL), () => _ufle12jhs77_F_AttackDamage = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_Cooldown;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_Cooldown => _ufle12jhs77_F_Cooldown ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5242321889616234573UL, 575571773611113602UL), () => _ufle12jhs77_F_Cooldown = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_MoveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_MoveSpeed => _ufle12jhs77_F_MoveSpeed ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4857341692010985426UL, 13584916197963286699UL), () => _ufle12jhs77_F_MoveSpeed = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_CritDamage;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_CritDamage => _ufle12jhs77_F_CritDamage ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4628428116117743647UL, 1371855942397048230UL), () => _ufle12jhs77_F_CritDamage = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_CritChance;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_CritChance => _ufle12jhs77_F_CritChance ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5490054195320435683UL, 6206484971106048130UL), () => _ufle12jhs77_F_CritChance = null);
	private DB_SwordStat() : base(MetaDefault) {}
	private DB_SwordStat(BGId id) : base(MetaDefault, id) {}
	private DB_SwordStat(BGMetaEntity meta) : base(meta) {}
	private DB_SwordStat(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_SwordStat FindEntity(Predicate<DB_SwordStat> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_SwordStat> FindEntities(Predicate<DB_SwordStat> filter, List<DB_SwordStat> result=null, Comparison<DB_SwordStat> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_SwordStat> action, Predicate<DB_SwordStat> filter=null, Comparison<DB_SwordStat> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_SwordStat GetEntity(BGId entityId) => (DB_SwordStat) MetaDefault.GetEntity(entityId);
	public static DB_SwordStat GetEntity(int index) => (DB_SwordStat) MetaDefault[index];
	public static DB_SwordStat GetEntity(string entityName) => (DB_SwordStat) MetaDefault.GetEntity(entityName);
	public static DB_SwordStat NewEntity() => (DB_SwordStat) MetaDefault.NewEntity();
	public static DB_SwordStat NewEntity(BGId entityId) => (DB_SwordStat) MetaDefault.NewEntity(entityId);
	public static DB_SwordStat NewEntity(Action<DB_SwordStat> callback) => (DB_SwordStat) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_SwordStat)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5409651157038217224UL,8990331384380502203UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5393742928008535207UL, 12160457354885359032UL));
		_ufle12jhs77_F_AttackDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(4719671630520485392UL, 13677255214246859924UL));
		_ufle12jhs77_F_Cooldown = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5242321889616234573UL, 575571773611113602UL));
		_ufle12jhs77_F_MoveSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4857341692010985426UL, 13584916197963286699UL));
		_ufle12jhs77_F_CritDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4628428116117743647UL, 1371855942397048230UL));
		_ufle12jhs77_F_CritChance = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5490054195320435683UL, 6206484971106048130UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_AttackDamage = null;
		_ufle12jhs77_F_Cooldown = null;
		_ufle12jhs77_F_MoveSpeed = null;
		_ufle12jhs77_F_CritDamage = null;
		_ufle12jhs77_F_CritChance = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_SwordStat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_SwordStat(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "SwordStat";
		public const string name = "name";
		public const string AttackDamage = "AttackDamage";
		public const string Cooldown = "Cooldown";
		public const string MoveSpeed = "MoveSpeed";
		public const string CritDamage = "CritDamage";
		public const string CritChance = "CritChance";
	}
}

[Preserve]
public sealed partial class DB_UpgradeData : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5087809049740838449UL,16974189131134665129UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.String F_DisplayName
	{
		get => _F_DisplayName[Index];
		set => _F_DisplayName[Index] = value;
	}
	public System.Double F_BaseCost
	{
		get => _F_BaseCost[Index];
		set => _F_BaseCost.SetValue(this, value);
	}
	public System.Single F_CostMultiplier
	{
		get => _F_CostMultiplier[Index];
		set => _F_CostMultiplier.SetValue(this, value);
	}
	public System.Double F_BonusPerLevel
	{
		get => _F_BonusPerLevel[Index];
		set => _F_BonusPerLevel.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4909339439856330490UL, 2018569692734414988UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_DisplayName;
	public static BansheeGz.BGDatabase.BGFieldString _F_DisplayName => _ufle12jhs77_F_DisplayName ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4655706310135044183UL, 10759528459962272931UL), () => _ufle12jhs77_F_DisplayName = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_BaseCost;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_BaseCost => _ufle12jhs77_F_BaseCost ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5640767517175005758UL, 14676626564300675253UL), () => _ufle12jhs77_F_BaseCost = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_CostMultiplier;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_CostMultiplier => _ufle12jhs77_F_CostMultiplier ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5249903429750701306UL, 11907952905357309824UL), () => _ufle12jhs77_F_CostMultiplier = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_BonusPerLevel;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_BonusPerLevel => _ufle12jhs77_F_BonusPerLevel ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4973888599178546572UL, 7264124440345813179UL), () => _ufle12jhs77_F_BonusPerLevel = null);
	private DB_UpgradeData() : base(MetaDefault) {}
	private DB_UpgradeData(BGId id) : base(MetaDefault, id) {}
	private DB_UpgradeData(BGMetaEntity meta) : base(meta) {}
	private DB_UpgradeData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_UpgradeData FindEntity(Predicate<DB_UpgradeData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_UpgradeData> FindEntities(Predicate<DB_UpgradeData> filter, List<DB_UpgradeData> result=null, Comparison<DB_UpgradeData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_UpgradeData> action, Predicate<DB_UpgradeData> filter=null, Comparison<DB_UpgradeData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_UpgradeData GetEntity(BGId entityId) => (DB_UpgradeData) MetaDefault.GetEntity(entityId);
	public static DB_UpgradeData GetEntity(int index) => (DB_UpgradeData) MetaDefault[index];
	public static DB_UpgradeData GetEntity(string entityName) => (DB_UpgradeData) MetaDefault.GetEntity(entityName);
	public static DB_UpgradeData NewEntity() => (DB_UpgradeData) MetaDefault.NewEntity();
	public static DB_UpgradeData NewEntity(BGId entityId) => (DB_UpgradeData) MetaDefault.NewEntity(entityId);
	public static DB_UpgradeData NewEntity(Action<DB_UpgradeData> callback) => (DB_UpgradeData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_UpgradeData)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5087809049740838449UL,16974189131134665129UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4909339439856330490UL, 2018569692734414988UL));
		_ufle12jhs77_F_DisplayName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4655706310135044183UL, 10759528459962272931UL));
		_ufle12jhs77_F_BaseCost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5640767517175005758UL, 14676626564300675253UL));
		_ufle12jhs77_F_CostMultiplier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5249903429750701306UL, 11907952905357309824UL));
		_ufle12jhs77_F_BonusPerLevel = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(4973888599178546572UL, 7264124440345813179UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_DisplayName = null;
		_ufle12jhs77_F_BaseCost = null;
		_ufle12jhs77_F_CostMultiplier = null;
		_ufle12jhs77_F_BonusPerLevel = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_UpgradeData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_UpgradeData(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "UpgradeData";
		public const string name = "name";
		public const string DisplayName = "DisplayName";
		public const string BaseCost = "BaseCost";
		public const string CostMultiplier = "CostMultiplier";
		public const string BonusPerLevel = "BonusPerLevel";
	}
}

[Preserve]
public sealed partial class DB_PlayerStat : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4708577541608124041UL,18293961910130488762UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.Double F_BaseMaxHealth
	{
		get => _F_BaseMaxHealth[Index];
		set => _F_BaseMaxHealth.SetValue(this, value);
	}
	public System.Single F_BaseMoveSpeed
	{
		get => _F_BaseMoveSpeed[Index];
		set => _F_BaseMoveSpeed.SetValue(this, value);
	}
	public System.Int32 F_Level
	{
		get => _F_Level[Index];
		set => _F_Level.SetValue(this, value);
	}
	public System.Double F_CurrentExp
	{
		get => _F_CurrentExp[Index];
		set => _F_CurrentExp.SetValue(this, value);
	}
	public System.Double F_MaxExp
	{
		get => _F_MaxExp[Index];
		set => _F_MaxExp.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5126616037073935819UL, 10770217428026799294UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_BaseMaxHealth;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_BaseMaxHealth => _ufle12jhs77_F_BaseMaxHealth ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5359559241489081077UL, 8203277029028940976UL), () => _ufle12jhs77_F_BaseMaxHealth = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_BaseMoveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_BaseMoveSpeed => _ufle12jhs77_F_BaseMoveSpeed ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4664648271635237836UL, 7265389442681811353UL), () => _ufle12jhs77_F_BaseMoveSpeed = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_Level;
	public static BansheeGz.BGDatabase.BGFieldInt _F_Level => _ufle12jhs77_F_Level ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5290958379428643078UL, 18120652675313612470UL), () => _ufle12jhs77_F_Level = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_CurrentExp;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_CurrentExp => _ufle12jhs77_F_CurrentExp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5284032231828068307UL, 14104316658382121374UL), () => _ufle12jhs77_F_CurrentExp = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_MaxExp;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_MaxExp => _ufle12jhs77_F_MaxExp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4951066478118912405UL, 13141334630425648546UL), () => _ufle12jhs77_F_MaxExp = null);
	private DB_PlayerStat() : base(MetaDefault) {}
	private DB_PlayerStat(BGId id) : base(MetaDefault, id) {}
	private DB_PlayerStat(BGMetaEntity meta) : base(meta) {}
	private DB_PlayerStat(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_PlayerStat FindEntity(Predicate<DB_PlayerStat> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_PlayerStat> FindEntities(Predicate<DB_PlayerStat> filter, List<DB_PlayerStat> result=null, Comparison<DB_PlayerStat> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_PlayerStat> action, Predicate<DB_PlayerStat> filter=null, Comparison<DB_PlayerStat> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_PlayerStat GetEntity(BGId entityId) => (DB_PlayerStat) MetaDefault.GetEntity(entityId);
	public static DB_PlayerStat GetEntity(int index) => (DB_PlayerStat) MetaDefault[index];
	public static DB_PlayerStat GetEntity(string entityName) => (DB_PlayerStat) MetaDefault.GetEntity(entityName);
	public static DB_PlayerStat NewEntity() => (DB_PlayerStat) MetaDefault.NewEntity();
	public static DB_PlayerStat NewEntity(BGId entityId) => (DB_PlayerStat) MetaDefault.NewEntity(entityId);
	public static DB_PlayerStat NewEntity(Action<DB_PlayerStat> callback) => (DB_PlayerStat) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_PlayerStat)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4708577541608124041UL,18293961910130488762UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5126616037073935819UL, 10770217428026799294UL));
		_ufle12jhs77_F_BaseMaxHealth = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5359559241489081077UL, 8203277029028940976UL));
		_ufle12jhs77_F_BaseMoveSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(4664648271635237836UL, 7265389442681811353UL));
		_ufle12jhs77_F_Level = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5290958379428643078UL, 18120652675313612470UL));
		_ufle12jhs77_F_CurrentExp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5284032231828068307UL, 14104316658382121374UL));
		_ufle12jhs77_F_MaxExp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(4951066478118912405UL, 13141334630425648546UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_BaseMaxHealth = null;
		_ufle12jhs77_F_BaseMoveSpeed = null;
		_ufle12jhs77_F_Level = null;
		_ufle12jhs77_F_CurrentExp = null;
		_ufle12jhs77_F_MaxExp = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_PlayerStat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_PlayerStat(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "PlayerStat";
		public const string name = "name";
		public const string BaseMaxHealth = "BaseMaxHealth";
		public const string BaseMoveSpeed = "BaseMoveSpeed";
		public const string Level = "Level";
		public const string CurrentExp = "CurrentExp";
		public const string MaxExp = "MaxExp";
	}
}

[Preserve]
public sealed partial class DB_PlayerProfile : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4841987156703711697UL,16310581820174931879UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.Double F_Gold
	{
		get => _F_Gold[Index];
		set => _F_Gold.SetValue(this, value);
	}
	public System.Double F_Ruby
	{
		get => _F_Ruby[Index];
		set => _F_Ruby.SetValue(this, value);
	}
	public System.Double F_UpgradeLevels
	{
		get => _F_UpgradeLevels[Index];
		set => _F_UpgradeLevels.SetValue(this, value);
	}
	public System.String F_LastLoginTime
	{
		get => _F_LastLoginTime[Index];
		set => _F_LastLoginTime[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4642974237642687383UL, 13473156798194563002UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_Gold;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_Gold => _ufle12jhs77_F_Gold ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5756689803566048807UL, 2847865984195918240UL), () => _ufle12jhs77_F_Gold = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_Ruby;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_Ruby => _ufle12jhs77_F_Ruby ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5565493530474271284UL, 2806272043107077512UL), () => _ufle12jhs77_F_Ruby = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_UpgradeLevels;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_UpgradeLevels => _ufle12jhs77_F_UpgradeLevels ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4654063876295627449UL, 5081672488624153999UL), () => _ufle12jhs77_F_UpgradeLevels = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_LastLoginTime;
	public static BansheeGz.BGDatabase.BGFieldString _F_LastLoginTime => _ufle12jhs77_F_LastLoginTime ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5524188386132115016UL, 2659897881835505309UL), () => _ufle12jhs77_F_LastLoginTime = null);
	private DB_PlayerProfile() : base(MetaDefault) {}
	private DB_PlayerProfile(BGId id) : base(MetaDefault, id) {}
	private DB_PlayerProfile(BGMetaEntity meta) : base(meta) {}
	private DB_PlayerProfile(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_PlayerProfile FindEntity(Predicate<DB_PlayerProfile> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_PlayerProfile> FindEntities(Predicate<DB_PlayerProfile> filter, List<DB_PlayerProfile> result=null, Comparison<DB_PlayerProfile> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_PlayerProfile> action, Predicate<DB_PlayerProfile> filter=null, Comparison<DB_PlayerProfile> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_PlayerProfile GetEntity(BGId entityId) => (DB_PlayerProfile) MetaDefault.GetEntity(entityId);
	public static DB_PlayerProfile GetEntity(int index) => (DB_PlayerProfile) MetaDefault[index];
	public static DB_PlayerProfile GetEntity(string entityName) => (DB_PlayerProfile) MetaDefault.GetEntity(entityName);
	public static DB_PlayerProfile NewEntity() => (DB_PlayerProfile) MetaDefault.NewEntity();
	public static DB_PlayerProfile NewEntity(BGId entityId) => (DB_PlayerProfile) MetaDefault.NewEntity(entityId);
	public static DB_PlayerProfile NewEntity(Action<DB_PlayerProfile> callback) => (DB_PlayerProfile) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_PlayerProfile)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4841987156703711697UL,16310581820174931879UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4642974237642687383UL, 13473156798194563002UL));
		_ufle12jhs77_F_Gold = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5756689803566048807UL, 2847865984195918240UL));
		_ufle12jhs77_F_Ruby = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5565493530474271284UL, 2806272043107077512UL));
		_ufle12jhs77_F_UpgradeLevels = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(4654063876295627449UL, 5081672488624153999UL));
		_ufle12jhs77_F_LastLoginTime = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5524188386132115016UL, 2659897881835505309UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_Gold = null;
		_ufle12jhs77_F_Ruby = null;
		_ufle12jhs77_F_UpgradeLevels = null;
		_ufle12jhs77_F_LastLoginTime = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_PlayerProfile(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_PlayerProfile(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "PlayerProfile";
		public const string name = "name";
		public const string Gold = "Gold";
		public const string Ruby = "Ruby";
		public const string UpgradeLevels = "UpgradeLevels";
		public const string LastLoginTime = "LastLoginTime";
	}
}

[Preserve]
public sealed partial class DB_BossStat : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4707457322595435855UL,12231758571260318640UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String F_name
	{
		get => _F_name[Index];
		set => _F_name[Index] = value;
	}
	public System.Double F_MaxHP
	{
		get => _F_MaxHP[Index];
		set => _F_MaxHP.SetValue(this, value);
	}
	public System.Double F_AttackDamage
	{
		get => _F_AttackDamage[Index];
		set => _F_AttackDamage.SetValue(this, value);
	}
	public System.Single F_MoveSpeed
	{
		get => _F_MoveSpeed[Index];
		set => _F_MoveSpeed.SetValue(this, value);
	}
	public System.Double F_GoldReward
	{
		get => _F_GoldReward[Index];
		set => _F_GoldReward.SetValue(this, value);
	}
	public System.Double F_Exp
	{
		get => _F_Exp[Index];
		set => _F_Exp.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name => _ufle12jhs77_F_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5360313446674402160UL, 9707935026252860851UL), () => _ufle12jhs77_F_name = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_MaxHP;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_MaxHP => _ufle12jhs77_F_MaxHP ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5600073837630038947UL, 12195307191774264994UL), () => _ufle12jhs77_F_MaxHP = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_AttackDamage;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_AttackDamage => _ufle12jhs77_F_AttackDamage ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4807780385995517877UL, 11845050730439917211UL), () => _ufle12jhs77_F_AttackDamage = null);
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_F_MoveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _F_MoveSpeed => _ufle12jhs77_F_MoveSpeed ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5676064908509143851UL, 3521916650749570957UL), () => _ufle12jhs77_F_MoveSpeed = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_GoldReward;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_GoldReward => _ufle12jhs77_F_GoldReward ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5140081250666088650UL, 16268987872243578550UL), () => _ufle12jhs77_F_GoldReward = null);
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_F_Exp;
	public static BansheeGz.BGDatabase.BGFieldDouble _F_Exp => _ufle12jhs77_F_Exp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5622818037148344789UL, 13117884331757214852UL), () => _ufle12jhs77_F_Exp = null);
	private DB_BossStat() : base(MetaDefault) {}
	private DB_BossStat(BGId id) : base(MetaDefault, id) {}
	private DB_BossStat(BGMetaEntity meta) : base(meta) {}
	private DB_BossStat(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_BossStat FindEntity(Predicate<DB_BossStat> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_BossStat> FindEntities(Predicate<DB_BossStat> filter, List<DB_BossStat> result=null, Comparison<DB_BossStat> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_BossStat> action, Predicate<DB_BossStat> filter=null, Comparison<DB_BossStat> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_BossStat GetEntity(BGId entityId) => (DB_BossStat) MetaDefault.GetEntity(entityId);
	public static DB_BossStat GetEntity(int index) => (DB_BossStat) MetaDefault[index];
	public static DB_BossStat GetEntity(string entityName) => (DB_BossStat) MetaDefault.GetEntity(entityName);
	public static DB_BossStat NewEntity() => (DB_BossStat) MetaDefault.NewEntity();
	public static DB_BossStat NewEntity(BGId entityId) => (DB_BossStat) MetaDefault.NewEntity(entityId);
	public static DB_BossStat NewEntity(Action<DB_BossStat> callback) => (DB_BossStat) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_BossStat)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4707457322595435855UL,12231758571260318640UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_F_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5360313446674402160UL, 9707935026252860851UL));
		_ufle12jhs77_F_MaxHP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5600073837630038947UL, 12195307191774264994UL));
		_ufle12jhs77_F_AttackDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(4807780385995517877UL, 11845050730439917211UL));
		_ufle12jhs77_F_MoveSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(_metaDefault, new BGId(5676064908509143851UL, 3521916650749570957UL));
		_ufle12jhs77_F_GoldReward = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5140081250666088650UL, 16268987872243578550UL));
		_ufle12jhs77_F_Exp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(_metaDefault, new BGId(5622818037148344789UL, 13117884331757214852UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_F_name = null;
		_ufle12jhs77_F_MaxHP = null;
		_ufle12jhs77_F_AttackDamage = null;
		_ufle12jhs77_F_MoveSpeed = null;
		_ufle12jhs77_F_GoldReward = null;
		_ufle12jhs77_F_Exp = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_BossStat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_BossStat(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "BossStat";
		public const string name = "name";
		public const string MaxHP = "MaxHP";
		public const string AttackDamage = "AttackDamage";
		public const string MoveSpeed = "MoveSpeed";
		public const string GoldReward = "GoldReward";
		public const string Exp = "Exp";
	}
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime()
	{
		DB_EnemyStat.InitializeCodeGenRuntime();
		DB_StageStat.InitializeCodeGenRuntime();
		DB_SwordStat.InitializeCodeGenRuntime();
		DB_UpgradeData.InitializeCodeGenRuntime();
		DB_PlayerStat.InitializeCodeGenRuntime();
		DB_PlayerProfile.InitializeCodeGenRuntime();
		DB_BossStat.InitializeCodeGenRuntime();
	}
	[Preserve]
	public static void ReleaseCodeGenRuntime()
	{
		DB_EnemyStat.ReleaseCodeGenRuntime();
		DB_StageStat.ReleaseCodeGenRuntime();
		DB_SwordStat.ReleaseCodeGenRuntime();
		DB_UpgradeData.ReleaseCodeGenRuntime();
		DB_PlayerStat.ReleaseCodeGenRuntime();
		DB_PlayerProfile.ReleaseCodeGenRuntime();
		DB_BossStat.ReleaseCodeGenRuntime();
	}
}
#pragma warning restore 414
